package inc.fabudi.lists

import java.util.Random


object UserGenerator {
    val users = ArrayList<User>()
    private val lastNames = listOf(
        "Smith",
        "Jones",
        "Taylor",
        "Williams",
        "Brown",
        "White",
        "Harris",
        "Martin",
        "Davies",
        "Wilson",
        "Cooper",
        "Evans",
        "King",
        "Thomas",
        "Baker",
        "Green",
        "Wright",
        "Johnson",
        "Edwards",
        "Clark",
        "Roberts",
        "Robinson",
        "Hall",
        "Lewis",
        "Clarke",
        "Young",
        "Davis",
        "Turner",
        "Hill",
        "Phillips",
        "Collins",
        "Allen",
        "Moore",
        "Thompson",
        "Carter",
        "James",
        "Knight",
        "Walker",
        "Wood",
        "Hughes",
        "Parker",
        "Ward",
        "Bennett",
        "Cook",
        "Webb",
        "Bailey",
        "Scott",
        "Jackson",
        "Lee",
        "Cox"
    )
    private val firstNames = listOf(
        "Wade",
        "Dave",
        "Seth",
        "Ivan",
        "Riley",
        "Gilbert",
        "Jorge",
        "Dan",
        "Brian",
        "Roberto",
        "Ramon",
        "Miles",
        "Liam",
        "Nathaniel",
        "Ethan",
        "Lewis",
        "Milton",
        "Claude",
        "Joshua",
        "Glen",
        "Harvey",
        "Blake",
        "Antonio",
        "Connor",
        "Julian",
        "Aidan",
        "Harold",
        "Conner",
        "Peter",
        "Hunter",
        "Eli",
        "Alberto",
        "Carlos",
        "Shane",
        "Aaron",
        "Marlin",
        "Paul",
        "Ricardo",
        "Hector",
        "Alexis",
        "Adrian",
        "Kingston",
        "Douglas",
        "Gerald",
        "Joey",
        "Johnny",
        "Charlie",
        "Scott",
        "Martin",
        "Tristin",
        "Troy",
        "Tommy",
        "Rick",
        "Victor",
        "Jessie",
        "Neil",
        "Ted",
        "Nick",
        "Wiley",
        "Morris",
        "Clark",
        "Stuart",
        "Orlando",
        "Keith",
        "Marion",
        "Marshall",
        "Noel",
        "Everett",
        "Romeo",
        "Sebastian",
        "Stefan",
        "Robin",
        "Clarence",
        "Sandy",
        "Ernest",
        "Samuel",
        "Benjamin",
        "Luka",
        "Fred",
        "Albert",
        "Greyson",
        "Terry",
        "Cedric",
        "Joe",
        "Paul",
        "George",
        "Bruce",
        "Christopher",
        "Mark",
        "Ron",
        "Craig",
        "Philip",
        "Jimmy",
        "Arthur",
        "Jaime",
        "Perry",
        "Harold",
        "Jerry",
        "Shawn",
        "Walter"
    )
    private val descriptions = listOf(
        "Aliquam fringilla elit eros, id sollicitudin enim pulvinar faucibus.",
        "Cras dignissim purus vel sapien scelerisque, non tempor nisl tincidunt.",
        "Fusce aliquet odio ipsum, sit amet varius dolor dapibus ut.",
        "Nunc tristique urna eu dui sollicitudin pretium.",
        "Ut egestas nisl eget sapien interdum sollicitudin.",
        "Vivamus sed mauris condimentum, suscipit odio et, eleifend odio.",
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
        "Donec eu consequat odio, at sagittis mi.",
        "Nullam aliquet, erat eu faucibus malesuada, magna sem congue diam, at accumsan metus est at dolor.",
        "Nulla euismod enim ut eros consectetur, et commodo ipsum tincidunt.Curabitur id mauris neque.",
        "Duis tempor purus lorem, at tempus urna ultrices sed.",
        "Quisque interdum quis tellus ut sagittis.",
        "Integer nec purus malesuada, efficitur purus sed, porta ligula.",
        "Phasellus eget consequat risus.",
        "Pellentesque tincidunt nulla eget felis maximus, non hendrerit nisl dictum.",
        "Curabitur consectetur metus vitae urna finibus luctus.",
        "Aliquam iaculis mattis eros id congue.",
        "Donec mollis rutrum sodales.",
        "Nullam aliquet molestie arcu, eu auctor elit facilisis eget.",
        "Phasellus sodales ante quis orci interdum, eu euismod eros tristique.",
        "Proin felis sem, varius sit amet tellus vitae, scelerisque feugiat ex.",
        "Aliquam et rhoncus enim.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
        "Suspendisse potenti.",
        "Nulla at fermentum enim, eu suscipit dui.",
        "Nulla facilisi.",
        "Nulla tincidunt risus et nulla pharetra, id dapibus mi faucibus.",
        "Proin mi ipsum, ultrices vel lectus in, euismod molestie est.",
        "Phasellus felis quam, bibendum non blandit eu, maximus nec nisi.",
        "Praesent mauris eros, ornare id leo at, pharetra venenatis risus.",
        "Vivamus nec tellus eget erat auctor volutpat.",
        "Nulla neque diam, pharetra eu metus et, ullamcorper rhoncus odio.",
        "Donec vulputate varius rutrum.",
        "Nulla facilisi.",
        "Phasellus maximus purus tempor tortor rhoncus, eu aliquam tellus venenatis.Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Sed pharetra nisl urna, in venenatis eros aliquam ut.",
        "Nunc malesuada arcu dictum dolor hendrerit venenatis.",
        "Nunc tincidunt nec ante et fringilla.",
        "Proin nulla odio, accumsan condimentum leo non, pretium ornare est.",
        "Suspendisse id volutpat urna, non molestie mauris.",
        "Mauris luctus varius risus sed fermentum.",
        "Cras pulvinar mi lacus, eu lacinia dolor convallis a.",
        "Ut mi nisl, pellentesque sit amet nisl a, lacinia commodo enim.",
        "Aliquam congue quam ut risus iaculis, sed varius nibh rhoncus.",
        "Vestibulum auctor, nulla at auctor fermentum, eros sapien pulvinar enim, at consectetur est nulla elementum dui.",
        "Donec finibus, est a sollicitudin pharetra, sapien lorem tristique eros, sit amet eleifend orci diam nec ligula.",
        "Sed nisi lacus, sollicitudin sit amet sagittis quis, commodo sit amet tellus.",
        "Sed ornare convallis quam vel porttitor.",
        "Fusce varius orci ut tortor cursus viverra.",
        "Praesent ac luctus dolor, rhoncus egestas nibh.Quisque vel rhoncus mauris, id cursus sem.",
        "Ut convallis neque ut volutpat varius.",
        "Vestibulum sit amet orci nisl.",
        "Integer pulvinar, est quis tristique ullamcorper, mauris diam lacinia magna, ut feugiat elit nulla et sapien.",
        "Pellentesque gravida diam at vestibulum vehicula.",
        "Mauris nec efficitur eros.",
        "Morbi malesuada, tellus finibus efficitur porta, libero urna fringilla risus, vel placerat arcu nisi nec dolor.",
        "Nulla ipsum ipsum, tempor a placerat eget, feugiat vitae dui.",
        "Vestibulum convallis urna ac augue mollis congue.",
        "Nulla eu purus erat.",
        "Praesent tincidunt mattis quam, et interdum dui aliquet sit amet.",
        "Mauris aliquam, nisl vel laoreet rhoncus, magna lorem fermentum justo, at efficitur dolor sem sit amet urna.",
    )

    init {
        for (i in 0..30) {
            users.add(
                User(
                    firstNames[Random().nextInt(100)],
                    lastNames[Random().nextInt(50)],
                    Random().nextInt(82)+18,
                    Sex.values()[Random().nextInt(2)+1],
                    "https://loremflickr.com/300/300?t=${System.currentTimeMillis()}",
                    descriptions[Random().nextInt(60)]
                )
            )
        }
    }

}